package com.example.seminar_management_system.presentation.screens.registeredUserInterface.homeScreen

import com.example.seminar_management_system.presentation.screens.registeredUserInterface.homeScreen.bookstate.Books

object BooksRepo {
    val heroes = listOf(
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        ),
        Books(
            1,
            "102736",
            "644460",
            "Sanjay K  Bose",
            "Hardware and Software of personal computer",
            "1",
            "3",
            "New Age International",
            "hardware",
            "software",
            "",
            "2002",
            "",
            "",
            ""
        )
    )
}